#!/usr/bin/env perl

use strict;
use warnings;

use lib 'lib';

# Start command line interface for application
require Mojolicious::Commands;
# this is the entry point of the application
Mojolicious::Commands->start_app('DocPub');
